spring:
  application:
    name: login-system

  profiles:
   active: test

---
# TEST (profile "test")
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:login-system
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  client-id: ${CLIENT_ID:myclientid}
  client-secret: ${CLIENT_SECRET:myclientsecret}
  jwt:
    duration: ${JWT_DURATION:86400}
    cors:
      origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}
